# Generated by Django 5.0.2 on 2024-03-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test2',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1'), ('Green', '2')], default='John Doe', max_length=122),
        ),
        migrations.AddField(
            model_name='test',
            name='test3',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1'), ('Green', '2')], default='John Doe', max_length=122),
        ),
        migrations.AddField(
            model_name='test',
            name='test4',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1'), ('Green', '2')], default='John Doe', max_length=122),
        ),
        migrations.AddField(
            model_name='test',
            name='test5',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1'), ('Green', '2')], default='John Doe', max_length=122),
        ),
        migrations.AddField(
            model_name='test',
            name='test6',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1'), ('Green', '2')], default='John Doe', max_length=122),
        ),
    ]
