# Generated by Django 5.0.2 on 2024-04-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_test_test2_test_test3_test_test4_test_test5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test10',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1')], default='John Doe', max_length=122),
        ),
        migrations.AddField(
            model_name='test',
            name='test7',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1')], default='John Doe', max_length=122),
        ),
        migrations.AddField(
            model_name='test',
            name='test8',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1')], default='John Doe', max_length=122),
        ),
        migrations.AddField(
            model_name='test',
            name='test9',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1'), ('Green', '2'), ('Black', '3')], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test2',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1'), ('Green', '2'), ('Black', '3')], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test3',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1'), ('Green', '2'), ('Black', '3')], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test4',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1')], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test5',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1')], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test6',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1')], default='John Doe', max_length=122),
        ),
    ]
