# Generated by Django 5.0.2 on 2024-04-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_test_test10_test_test7_test_test8_test_test9_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test1',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1'), ('Green', '2')], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test3',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1'), ('Green', '2')], default='John Doe', max_length=122),
        ),
    ]
