# Generated by Django 5.0.2 on 2024-04-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_test_test1_alter_test_test3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test1',
            field=models.CharField(choices=[('Red', '1'), ('Blue', '2'), ('Green', '3'), ('Black', '4')], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test2',
            field=models.CharField(choices=[('Red', '1'), ('Blue', '2'), ('Green', '3'), ('Black', '4')], default='John Doe', max_length=122),
        ),
    ]
