# Generated by Django 5.0.2 on 2024-04-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_test_test1_alter_test_test2'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test11',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1')], default='John Doe', max_length=122),
        ),
        migrations.AddField(
            model_name='test',
            name='test12',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1')], default='John Doe', max_length=122),
        ),
        migrations.AddField(
            model_name='test',
            name='test13',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1')], default='John Doe', max_length=122),
        ),
        migrations.AddField(
            model_name='test',
            name='test14',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1')], default='John Doe', max_length=122),
        ),
        migrations.AddField(
            model_name='test',
            name='test15',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='John Doe', max_length=122),
        ),
        migrations.AddField(
            model_name='test',
            name='test16',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='John Doe', max_length=122),
        ),
        migrations.AddField(
            model_name='test',
            name='test17',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test3',
            field=models.CharField(choices=[('Red', '1'), ('Blue', '1'), ('Green', '2'), ('Black', '4')], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test4',
            field=models.CharField(choices=[('Red', '1'), ('Blue', '2'), ('Green', '3'), ('Black', '4')], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test9',
            field=models.CharField(choices=[('Red', '0'), ('Blue', '1')], default='John Doe', max_length=122),
        ),
    ]
