# Generated by Django 5.0.2 on 2024-04-15 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_test_test11_test_test12_test_test13_test_test14_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 15, 14, 3, 8, 575722), verbose_name='Date'),
        ),
    ]
