# Generated by Django 5.0.2 on 2024-04-15 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_test_date_alter_test_test15_alter_test_test16_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 15, 14, 35, 25, 613115), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test15',
            field=models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8'), ('nine', '9')], default='John Doe', max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='test16',
            field=models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8')], default='John Doe', max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='test17',
            field=models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8')], default='John Doe', max_length=255),
        ),
    ]
