# Generated by Django 5.0.2 on 2024-04-15 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_test_date_alter_test_test15_alter_test_test16_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 15, 16, 26, 45, 243239), verbose_name='Date'),
        ),
    ]
