# Generated by Django 5.0.2 on 2024-04-15 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 15, 16, 43, 6, 598931), verbose_name='Date'),
        ),
    ]
