# Generated by Django 5.0.2 on 2024-04-15 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 15, 17, 2, 34, 348488), verbose_name='Date'),
        ),
    ]
