# Generated by Django 5.0.2 on 2024-04-15 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 15, 22, 45, 38, 717211), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test1',
            field=models.CharField(choices=[('Red', 1), ('Blue', 2), ('Green', 3), ('Black', 4)], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test10',
            field=models.CharField(choices=[('Red', 0), ('Blue', 1)], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test11',
            field=models.CharField(choices=[('Red', 0), ('Blue', 1)], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test12',
            field=models.CharField(choices=[('Red', 0), ('Blue', 1)], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test13',
            field=models.CharField(choices=[('Red', 0), ('Blue', 1)], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test14',
            field=models.CharField(choices=[('Red', 0), ('Blue', 1)], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test15',
            field=models.CharField(choices=[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5), ('six', 6), ('seven', 7), ('eight', 8), ('nine', 9)], default='John Doe', max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='test16',
            field=models.CharField(choices=[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5), ('six', 6), ('seven', 7), ('eight', 8)], default='John Doe', max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='test17',
            field=models.CharField(choices=[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5), ('six', 6), ('seven', 7), ('eight', 8)], default='John Doe', max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='test2',
            field=models.CharField(choices=[('Red', 1), ('Blue', 2), ('Green', 3), ('Black', 4)], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test3',
            field=models.CharField(choices=[('Red', 1), ('Blue', 1), ('Green', 2), ('Black', 4)], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test4',
            field=models.CharField(choices=[('Red', 1), ('Blue', 2), ('Green', 3), ('Black', 4)], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test5',
            field=models.CharField(choices=[('Red', 0), ('Blue', 1)], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test6',
            field=models.CharField(choices=[('Red', 0), ('Blue', 1)], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test7',
            field=models.CharField(choices=[('Red', 0), ('Blue', 1)], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test8',
            field=models.CharField(choices=[('Red', 0), ('Blue', 1)], default='John Doe', max_length=122),
        ),
        migrations.AlterField(
            model_name='test',
            name='test9',
            field=models.CharField(choices=[('Red', 0), ('Blue', 1)], default='John Doe', max_length=122),
        ),
    ]
