# Generated by Django 5.0.2 on 2024-04-15 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_test_date_alter_test_test1_alter_test_test10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 15, 22, 49, 32, 271410), verbose_name='Date'),
        ),
    ]
