# Generated by Django 5.0.2 on 2024-05-14 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 14, 18, 4, 50, 498899), verbose_name='Date'),
        ),
    ]
