# Generated by Django 5.0.2 on 2024-05-14 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='email',
            field=models.CharField(default='John Doe', max_length=122),
        ),
        migrations.AddField(
            model_name='test',
            name='phone',
            field=models.CharField(default='johnDoe29@gmail.com', max_length=12),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 14, 18, 20, 54, 519264), verbose_name='Date'),
        ),
    ]
